/*
 * Generated by Robotoworks Mechanoid
 */
package com.aliensoft.elmatba5el3araby.ops;

import java.util.HashMap;

import com.robotoworks.mechanoid.ops.OperationConfigurationRegistry;
import com.robotoworks.mechanoid.ops.OperationConfiguration;

public abstract class AbstractRecipesServiceOperationConfigurationRegistry extends OperationConfigurationRegistry {
	
	private HashMap<String, OperationConfiguration> mOperationConfigurations;
	
	public AbstractRecipesServiceOperationConfigurationRegistry() {
		
		mOperationConfigurations = new HashMap<String, OperationConfiguration>();
		
		registerOperationConfigurations();
	}
	
	protected void registerOperationConfigurations(){
		registerOperationConfiguration(ImportDataFromFileOperation.ACTION_IMPORT_DATA_FROM_FILE, new ImportDataFromFileOperation.Configuration());
	}
	
	protected void registerOperationConfiguration(String action, OperationConfiguration config) {
		mOperationConfigurations.put(action, config);
	}

	@Override
	public OperationConfiguration getOperationConfiguration(String action) {
		return mOperationConfigurations.get(action);
	}
}
