/*
 * Generated by Robotoworks Mechanoid
 */
package com.aliensoft.elmatba5el3araby.ops;

import com.aliensoft.elmatba5el3araby.ops.RecipesServiceProcessor;
import com.robotoworks.mechanoid.ops.OperationProcessor;
import com.robotoworks.mechanoid.ops.OperationService;
import com.robotoworks.mechanoid.ops.OperationServiceConfiguration;

public abstract class AbstractRecipesService extends OperationService {
	
	public static final OperationServiceConfiguration CONFIG = new RecipesServiceConfiguration();
	
	@Override
	protected OperationProcessor createProcessor() {
		return new RecipesServiceProcessor(this);
	}
	
	public AbstractRecipesService(boolean enableLogging) {
		super(enableLogging);
	}
}
