/*
 * Generated by Robotoworks Mechanoid
 */
package com.aliensoft.elmatba5el3araby.ops;

import com.robotoworks.mechanoid.ops.Operation;
import com.robotoworks.mechanoid.ops.OperationService;
import com.robotoworks.mechanoid.ops.OperationProcessor;			

public abstract class AbstractRecipesServiceProcessor extends OperationProcessor {

	@Override
	protected Operation createOperation(String action) {
		return RecipesService.CONFIG
			.getOperationConfigurationRegistry()
			.getOperationConfiguration(action)
			.createOperation();
	}
	
	public AbstractRecipesServiceProcessor(OperationService service, boolean enableLogging) {
		super(service, enableLogging);
	}
}
