/*
 * Generated by Robotoworks Mechanoid
 */
package com.aliensoft.elmatba5el3araby.ops;

import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.ops.Operation;
import com.robotoworks.mechanoid.ops.OperationContext;
import com.robotoworks.mechanoid.ops.OperationResult;
import com.robotoworks.mechanoid.ops.OperationServiceBridge;
import com.robotoworks.mechanoid.ops.OperationConfiguration;
import android.content.Intent;
import android.os.Bundle;

public abstract class AbstractImportDataFromFileOperation extends Operation {
	public static final String ACTION_IMPORT_DATA_FROM_FILE = "eu.masconsult.template.recipes.ops.RecipesService.actions.IMPORT_DATA_FROM_FILE";

	public static final String EXTRA_FILENAME = "eu.masconsult.template.recipes.ops.RecipesService.extras.FILENAME";

	static class Args {
		public String filename;
	}
	
	static class Configuration extends OperationConfiguration {
		@Override 
		public Operation createOperation() {
			return new ImportDataFromFileOperation();
		}
		
		@Override
		public Intent findMatchOnConstraint(OperationServiceBridge bridge, Intent intent) {
			Intent existingRequest = bridge.findPendingRequestByActionWithExtras(AbstractImportDataFromFileOperation.ACTION_IMPORT_DATA_FROM_FILE, intent.getExtras());
			
			return existingRequest;
			
		}
	}
	
	public static final Intent newIntent(String filename) {
		Intent intent = new Intent(ACTION_IMPORT_DATA_FROM_FILE);
		intent.setClass(Mechanoid.getApplicationContext(), RecipesService.class);
		
		Bundle extras = new Bundle();
		extras.putString(EXTRA_FILENAME, filename);
		
		intent.putExtras(extras);
		
		return intent;
		
	}

	@Override
	public OperationResult execute(OperationContext context) {
		Args args = new Args();
		
		Bundle extras = context.getIntent().getExtras();
		args.filename = extras.getString(EXTRA_FILENAME);
		
		return onExecute(context, args);
	}
			
	protected abstract OperationResult onExecute(OperationContext context, Args args);
}
