/*
 * Generated by Robotoworks Mechanoid
 */
package com.aliensoft.elmatba5el3araby.ops;

import com.robotoworks.mechanoid.ops.OperationService;

public class RecipesServiceProcessor extends AbstractRecipesServiceProcessor {
	public RecipesServiceProcessor(OperationService service) {
		super(service, false);
	}
}
