/*
 * Generated by Robotoworks Mechanoid
 */
package com.aliensoft.elmatba5el3araby.ops;

import com.aliensoft.elmatba5el3araby.ops.AbstractRecipesService;

public class RecipesService extends AbstractRecipesService {
	public RecipesService() {
		super(false);
	}
}
