/*
 * Generated by Robotoworks Mechanoid
 */
package com.aliensoft.elmatba5el3araby.ops;

public class RecipesServiceOperationConfigurationRegistry extends AbstractRecipesServiceOperationConfigurationRegistry {
	
}

