/*
 * Generated by Robotoworks Mechanoid
 */
package com.aliensoft.elmatba5el3araby.content;

import com.aliensoft.elmatba5el3araby.content.AbstractRecipesDBOpenHelper;

import android.content.Context;

public class RecipesDBOpenHelper extends AbstractRecipesDBOpenHelper {
	public RecipesDBOpenHelper(Context context) {
		super(context);
	}
}
